// Generated by editor
interface VariableType {
    [key: string]: string | number;
}

export interface GlobalVariableType extends VariableType {
}

export interface RecordVariableType extends VariableType {
}

export const globalVariableConstrains: { [key: string]: { min?: number, max?: number } } = {
}

export const recordVariableConstrains: { [key: string]: { min?: number, max?: number } } = {
}

export const defaultGlobalVariables: GlobalVariableType = {
}

export const defaultRecordVariables: RecordVariableType = {
}
