import { ResUtils } from "../utils/ResUtils";
import { PlotData } from "../react/avg/model/PlotModel";

// Generated by editor
type PlotDataType = { firstPlot: string, entries: { [key: string]: string } };

const plotsData: PlotDataType = {
    firstPlot: "",
    entries: {}
};

export function getPlotsData(): DeepReadonly<PlotDataType> {
    return plotsData;
}

export async function getPlotData(plot: string) {
    let data = await ResUtils.loadRes<PlotData>("plots/" + plotsData.entries[plot]);
    ResUtils.releaseRes("plots/" + plotsData.entries[plot]);
    return data;
}