import { Emitter } from "./utils/EventKit";

const emitter = new Emitter;
export const WindowResizeEvent = emitter.createEvent<(width: number, height: number) => void>();
export const WidgetUpdateEvent = emitter.createEvent<() => void>();
export const MusicVolumeChange = emitter.createEvent<(volume: number) => void>();
export const SoundVolumeChange = emitter.createEvent<(volume: number) => void>();
export const PlotStartEvent = emitter.createEvent<(plotId: string) => void>();
export const PlotButtonEvent = emitter.createEvent<(buttonKey: string) => void>();

export namespace GameEvents {
    export const emitter = new Emitter;
    export const SHOW_UI_START = emitter.createEvent<() => void>("SHOW_UI_START");
    export const SHOW_UI_RECORD = emitter.createEvent<() => void>("SHOW_UI_RECORD");
    export const SHOW_UI_SETTING = emitter.createEvent<() => void>("SHOW_UI_SETTING");
    export const START_PLOT = emitter.createEvent<(plotId: string) => void>("START_PLOT");
    export const END_CURRENT_DIALOG = emitter.createEvent<() => void>("END_CURRENT_DIALOG");
    export const ON_DIALOG_BEGIN = emitter.createEvent<(name: string) => void>("ON_DIALOG_BEGIN");
    export const ON_DIALOG_END = emitter.createEvent<(name: string) => void>("ON_DIALOG_END");
    // Generated by Editor
}